### ISSUE TITLE
Global registry connector for Messaging Nodes

### ISSUE THREAD

**Issue by sdruesedow** [reTHINK-project/dev-registry-global#16]
During the WP3 telco it was discussed that the global registry should also be accessed via the Messaging Nodes, comparable to the mechanism for the domain registry. For that purpose the MNs have to implement a Connector (Vertx already started this). 

Since the GR is not inside MNs domain and there can be more than one Global Registry several questions popped up during the discussion:
- Each MN has to maintain its own list of GRs?
- Which registries shall the MN contact - special order/filtering ?
- Where does it get the URLs from?
- Which policy to apply if there is more than one result? (first, merged or leave it up to the MNs impl ?)

**Comment by sgoendoer** [comment]
The GReg is a (one) directory service. There are not multiple isolated instances. All "nodes" are connected via a DHT. Meaning: What you write "to" one node, you can read "from" any other node of the GReg.

Regarding to your questions:

- As the GR nodes are connected, a MN would need to have at least one GR node in a list, e.g. a config file. See https://github.com/reTHINK-project/dev-msg-node-vertx/blob/master/node.config.json#L8
- If there are multiple GReg nodes, this should/could be handled similar to the DNS: Having a primary, secondary, .... GReg node
- The GReg endpoints need to be configured at some point. A possible enhanced solution would be to let the MN periodically query "GET greg.domain.com:5002/" and add all "connected-nodes" in the status report for possible GReg endpoints in the future.
- Same as question 2
