### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by sgoendoer** [reTHINK-project/dev-registry-global#9]
As of now, deployment of the GlobalRegistry has to be done manually. A detailed step-by-step description can be found in the Wiki: https://github.com/reTHINK-project/dev-registry-global/wiki/Deployment-on-Debian-Ubuntu. For the future, a Docker image should be created.

**Comment by sbecot** [comment]
The page  
>  https://github.com/reTHINK-project/dev-registry-global/wiki/Deployment-on-Debian-Ubuntu.    

doesn't exist (any more?). The process to build on ubuntu is unclear, I tried to use maven (without eclipse) but I have dependencies issues.

**Comment by sgoendoer** [comment]
Hello, the Page still exists and is reachable via https://github.com/reTHINK-project/dev-registry-global/wiki/Deployment-on-Debian-Ubuntu:

Anyhow, we are currently working on a Spring-based, dockerized version of the GReg that will probably be much easier to setup and maintain.

**Comment by sbecot** [comment]
Ok, thank you, but I notice that this page doesn't explain how to compile it without eclipse. Maybe the D6.1 will help

**Comment by sgoendoer** [comment]
There’s another wiki page for the build process:

https://github.com/reTHINK-project/dev-registry-global/wiki/Building-GReg-via-Eclipse-Maven


--
Dipl.-Inform. Sebastian Göndör

Telekom Innovation Laboratories | TU Berlin
Service-centric Networking (SNET)

Ernst-Reuter-Platz 7 | TEL 19 | 10587 Berlin | Germany

Phone:  +49 (30) 8353-58166
Mobile: +49 160 4794391

sebastian.goendoer@tu-berlin.de<mailto:sebastian.goendoer@tu-berlin.de>

http://www.snet.tu-berlin.de/
http://www.laboratories.telekom.de/

**Comment by sgoendoer** [comment]
Please confer to https://github.com/reTHINK-project/dev-registry-global/wiki/Building-GReg-via-Eclipse-Maven

**Comment by sbecot** [comment]
Well _without Eclipse_ :-).

**Comment by sgoendoer** [comment]
Are you using any other IDE? IntelliJ perhaps?

**Comment by emmelmann-fokus** [comment]
Just a side note:  installation should also work without an IDE, right?!

**Comment by sbecot** [comment]
Right, I just want to: git clone, configure, build, run. Or even just run if a docker image is available. 
Anyway, this is a testbed machine, so I don't have any IDE on it, I just access throught putty.
Each block of the project has a different techno: java, node, etc... Installating a complete development suite for each one is not possible.

**Comment by emmelmann-fokus** [comment]
Please note that for WP-6, the final result will have to be provided in a docker that is ready to run anyway as we agreed to move towards docker compose for providing (backbone) testbed components.

**Comment by sbecot** [comment]
Ok.
We are then waiting for the docker version. By the way, we managed to install it, it is accessible here 
http://161.106.2.23:5002/
